
CREATE TABLE IF NOT EXISTS servers (
	id INTEGER PRIMARY KEY,
	url TEXT UNIQUE NOT NULL,
	port INTEGER DEFAULT 25565 NOT NULL
);

CREATE TABLE IF NOT EXISTS server_status (
	server_id INTEGER NOT NULL,
	time INTEGER NOT NULL,
	count INTEGER NOT NULL,
	PRIMARY KEY (server_id, time),
	FOREIGN KEY (server_id) REFERENCES servers(id) ON DELETE CASCADE
);
